//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrapbooker_Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int id { get; set; }
        public string fileName { get; set; }
        public string filePath { get; set; }
        public string fileFormat { get; set; }
        public double fileSize { get; set; }
        public string description { get; set; }
    }
}
