//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrapbooker_Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationDBEntities1 : DbContext
    {
        public ApplicationDBEntities1()
            : base("name=ApplicationDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<ImagesInAlbum> ImagesInAlbums { get; set; }
        public virtual DbSet<ImagesWithTag> ImagesWithTags { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
